services:
    pghost:
        image: postgres:16
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        container_name: nix
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            pghost:
                condition: service_healthy
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    postgres_data:
# Pour construire et exécuter l'ensemble de la pile :
# docker-compose up --build
#
# Pour exécuter en mode détaché :
# docker-compose up --build -d
#
# Pour arrêter la pile :
# docker-compose down
